# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui_italoKCGrTl.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

import numpy as np
from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(911, 732)
        self.actionAbrirImagem1 = QAction(MainWindow)
        self.actionAbrirImagem1.setObjectName(u"actionAbrirImagem1")
        self.actionAbrirImagem2 = QAction(MainWindow)
        self.actionAbrirImagem2.setObjectName(u"actionAbrirImagem2")
        self.actionSalvarResultado = QAction(MainWindow)
        self.actionSalvarResultado.setObjectName(u"actionSalvarResultado")
        self.actionSair = QAction(MainWindow)
        self.actionSair.setObjectName(u"actionSair")
        self.actionTonsDeCinza = QAction(MainWindow)
        self.actionTonsDeCinza.setObjectName(u"actionTonsDeCinza")
        self.actionPretoBranco = QAction(MainWindow)
        self.actionPretoBranco.setObjectName(u"actionPretoBranco")
        self.actionSoma = QAction(MainWindow)
        self.actionSoma.setObjectName(u"actionSoma")
        self.actionSubtracao = QAction(MainWindow)
        self.actionSubtracao.setObjectName(u"actionSubtracao")
        self.actionMultiplicacao = QAction(MainWindow)
        self.actionMultiplicacao.setObjectName(u"actionMultiplicacao")
        self.actionDivisao = QAction(MainWindow)
        self.actionDivisao.setObjectName(u"actionDivisao")
        self.actionNOT = QAction(MainWindow)
        self.actionNOT.setObjectName(u"actionNOT")
        self.actionAND = QAction(MainWindow)
        self.actionAND.setObjectName(u"actionAND")
        self.actionOR = QAction(MainWindow)
        self.actionOR.setObjectName(u"actionOR")
        self.actionXOR = QAction(MainWindow)
        self.actionXOR.setObjectName(u"actionXOR")
        self.actionTranslacao = QAction(MainWindow)
        self.actionTranslacao.setObjectName(u"actionTranslacao")
        self.actionRotacao = QAction(MainWindow)
        self.actionRotacao.setObjectName(u"actionRotacao")
        self.actionEscalonamento = QAction(MainWindow)
        self.actionEscalonamento.setObjectName(u"actionEscalonamento")
        self.actionDerivativo1 = QAction(MainWindow)
        self.actionDerivativo1.setObjectName(u"actionDerivativo1")
        self.actionDerivativo2 = QAction(MainWindow)
        self.actionDerivativo2.setObjectName(u"actionDerivativo2")
        self.actionSobel = QAction(MainWindow)
        self.actionSobel.setObjectName(u"actionSobel")
        self.actionKirsch = QAction(MainWindow)
        self.actionKirsch.setObjectName(u"actionKirsch")
        self.actionGerarHistograma = QAction(MainWindow)
        self.actionGerarHistograma.setObjectName(u"actionGerarHistograma")
        self.actionAutoescala = QAction(MainWindow)
        self.actionAutoescala.setObjectName(u"actionAutoescala")
        self.actionEqualizacaoDeHistograma = QAction(MainWindow)
        self.actionEqualizacaoDeHistograma.setObjectName(u"actionEqualizacaoDeHistograma")
        self.actionLimiarizacaoGlobal = QAction(MainWindow)
        self.actionLimiarizacaoGlobal.setObjectName(u"actionLimiarizacaoGlobal")
        self.actionLimiarizacaoDeOtsu = QAction(MainWindow)
        self.actionLimiarizacaoDeOtsu.setObjectName(u"actionLimiarizacaoDeOtsu")
        self.actionFiltroDeMedia = QAction(MainWindow)
        self.actionFiltroDeMedia.setObjectName(u"actionFiltroDeMedia")
        self.actionFiltroDeMediana = QAction(MainWindow)
        self.actionFiltroDeMediana.setObjectName(u"actionFiltroDeMediana")
        self.actionFiltroPassaAlta = QAction(MainWindow)
        self.actionFiltroPassaAlta.setObjectName(u"actionFiltroPassaAlta")
        self.actionLaplaciano = QAction(MainWindow)
        self.actionLaplaciano.setObjectName(u"actionLaplaciano")
        self.actionDilatacao = QAction(MainWindow)
        self.actionDilatacao.setObjectName(u"actionDilatacao")
        self.actionErosao = QAction(MainWindow)
        self.actionErosao.setObjectName(u"actionErosao")
        self.actionAbertura = QAction(MainWindow)
        self.actionAbertura.setObjectName(u"actionAbertura")
        self.actionFechamento = QAction(MainWindow)
        self.actionFechamento.setObjectName(u"actionFechamento")
        self.actionSegmentacaoProposta = QAction(MainWindow)
        self.actionSegmentacaoProposta.setObjectName(u"actionSegmentacaoProposta")
        self.actionExtracaodeCaracteristicas = QAction(MainWindow)
        self.actionExtracaodeCaracteristicas.setObjectName(u"actionExtracaodeCaracteristicas")
        self.actionTransformadaDeHough = QAction(MainWindow)
        self.actionTransformadaDeHough.setObjectName(u"actionTransformadaDeHough")
        self.actionCorrecaoDeOrientacao = QAction(MainWindow)
        self.actionCorrecaoDeOrientacao.setObjectName(u"actionCorrecaoDeOrientacao")
        self.actionOCR = QAction(MainWindow)
        self.actionOCR.setObjectName(u"actionOCR")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.janela_img1 = QLabel(self.centralwidget)
        self.janela_img1.setObjectName(u"janela_img1")
        self.janela_img1.setGeometry(QRect(10, 30, 400, 300))
        self.janela_img1.setFrameShape(QFrame.Box)
        self.janela_img1.setAlignment(Qt.AlignCenter)
        self.janela_img2 = QLabel(self.centralwidget)
        self.janela_img2.setObjectName(u"janela_img2")
        self.janela_img2.setGeometry(QRect(500, 30, 400, 300))
        self.janela_img2.setFrameShape(QFrame.Box)
        self.janela_img2.setAlignment(Qt.AlignCenter)
        self.janela_img_res = QLabel(self.centralwidget)
        self.janela_img_res.setObjectName(u"janela_img_res")
        self.janela_img_res.setGeometry(QRect(10, 380, 400, 300))
        self.janela_img_res.setFrameShape(QFrame.Box)
        self.janela_img_res.setAlignment(Qt.AlignCenter)
        self.janela_img_aux = QLabel(self.centralwidget)
        self.janela_img_aux.setObjectName(u"janela_img_aux")
        self.janela_img_aux.setGeometry(QRect(500, 380, 400, 300))
        self.janela_img_aux.setFrameShape(QFrame.Box)
        self.janela_img_aux.setAlignment(Qt.AlignCenter)
        self.botaoUseResultado = QPushButton(self.centralwidget)
        self.botaoUseResultado.setObjectName(u"botaoUseResultado")
        self.botaoUseResultado.setGeometry(QRect(270, 340, 111, 31))
        self.Slider = QSlider(self.centralwidget)
        self.Slider.setObjectName(u"Slider")
        self.Slider.setEnabled(False)
        self.Slider.setGeometry(QRect(420, 30, 22, 301))
        self.Slider.setLayoutDirection(Qt.LeftToRight)
        self.Slider.setMaximum(255)
        self.Slider.setSliderPosition(127)
        self.Slider.setTracking(True)
        self.Slider.setOrientation(Qt.Vertical)
        self.Slider.setInvertedAppearance(False)
        self.Slider.setInvertedControls(False)
        self.Slider.setTickPosition(QSlider.NoTicks)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setEnabled(True)
        self.label.setGeometry(QRect(190, 10, 71, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(680, 10, 71, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QRect(190, 360, 61, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QRect(680, 360, 47, 13))
        self.label_4.setTextFormat(Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_Slider_valor = QLabel(self.centralwidget)
        self.label_Slider_valor.setObjectName(u"label_Slider_valor")
        self.label_Slider_valor.setGeometry(QRect(450, 170, 31, 16))
        self.label_Slider_min = QLabel(self.centralwidget)
        self.label_Slider_min.setObjectName(u"label_Slider_min")
        self.label_Slider_min.setGeometry(QRect(450, 310, 31, 16))
        self.label_Slider_max = QLabel(self.centralwidget)
        self.label_Slider_max.setObjectName(u"label_Slider_max")
        self.label_Slider_max.setGeometry(QRect(450, 30, 31, 16))
        self.label_Slider = QLabel(self.centralwidget)
        self.label_Slider.setObjectName(u"label_Slider")
        self.label_Slider.setGeometry(QRect(420, 10, 61, 16))
        self.botaoMoveParaAuxiliar = QPushButton(self.centralwidget)
        self.botaoMoveParaAuxiliar.setObjectName(u"botaoMoveParaAuxiliar")
        self.botaoMoveParaAuxiliar.setGeometry(QRect(440, 470, 31, 111))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 911, 30))
        self.menuAbrir = QMenu(self.menubar)
        self.menuAbrir.setObjectName(u"menuAbrir")
        self.menuConverter = QMenu(self.menubar)
        self.menuConverter.setObjectName(u"menuConverter")
        self.menuOperacoes = QMenu(self.menubar)
        self.menuOperacoes.setObjectName(u"menuOperacoes")
        self.menuTransformacoesGeometricas = QMenu(self.menubar)
        self.menuTransformacoesGeometricas.setObjectName(u"menuTransformacoesGeometricas")
        self.menuDeteccaodeBordas = QMenu(self.menubar)
        self.menuDeteccaodeBordas.setObjectName(u"menuDeteccaodeBordas")
        self.menuHistograma = QMenu(self.menubar)
        self.menuHistograma.setObjectName(u"menuHistograma")
        self.menuFiltro = QMenu(self.menubar)
        self.menuFiltro.setObjectName(u"menuFiltro")
        self.menuMorfologia = QMenu(self.menubar)
        self.menuMorfologia.setObjectName(u"menuMorfologia")
        self.menuSegmentacao = QMenu(self.menubar)
        self.menuSegmentacao.setObjectName(u"menuSegmentacao")
        self.menuCaracteristicas = QMenu(self.menubar)
        self.menuCaracteristicas.setObjectName(u"menuCaracteristicas")
        self.menuOCR = QMenu(self.menubar)
        self.menuOCR.setObjectName(u"menuOCR")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAbrir.menuAction())
        self.menubar.addAction(self.menuConverter.menuAction())
        self.menubar.addAction(self.menuOperacoes.menuAction())
        self.menubar.addAction(self.menuTransformacoesGeometricas.menuAction())
        self.menubar.addAction(self.menuDeteccaodeBordas.menuAction())
        self.menubar.addAction(self.menuHistograma.menuAction())
        self.menubar.addAction(self.menuFiltro.menuAction())
        self.menubar.addAction(self.menuMorfologia.menuAction())
        self.menubar.addAction(self.menuSegmentacao.menuAction())
        self.menubar.addAction(self.menuCaracteristicas.menuAction())
        self.menubar.addAction(self.menuOCR.menuAction())
        self.menuAbrir.addAction(self.actionAbrirImagem1)
        self.menuAbrir.addAction(self.actionAbrirImagem2)
        self.menuAbrir.addAction(self.actionSalvarResultado)
        self.menuAbrir.addAction(self.actionSair)
        self.menuConverter.addAction(self.actionTonsDeCinza)
        self.menuConverter.addAction(self.actionPretoBranco)
        self.menuOperacoes.addAction(self.actionSoma)
        self.menuOperacoes.addAction(self.actionSubtracao)
        self.menuOperacoes.addAction(self.actionMultiplicacao)
        self.menuOperacoes.addAction(self.actionDivisao)
        self.menuOperacoes.addSeparator()
        self.menuOperacoes.addAction(self.actionNOT)
        self.menuOperacoes.addAction(self.actionAND)
        self.menuOperacoes.addAction(self.actionOR)
        self.menuOperacoes.addAction(self.actionXOR)
        self.menuTransformacoesGeometricas.addAction(self.actionTranslacao)
        self.menuTransformacoesGeometricas.addAction(self.actionRotacao)
        self.menuTransformacoesGeometricas.addAction(self.actionEscalonamento)
        self.menuDeteccaodeBordas.addAction(self.actionDerivativo1)
        self.menuDeteccaodeBordas.addAction(self.actionDerivativo2)
        self.menuDeteccaodeBordas.addAction(self.actionSobel)
        self.menuDeteccaodeBordas.addAction(self.actionKirsch)
        self.menuHistograma.addAction(self.actionGerarHistograma)
        self.menuHistograma.addAction(self.actionAutoescala)
        self.menuHistograma.addAction(self.actionEqualizacaoDeHistograma)
        self.menuHistograma.addAction(self.actionLimiarizacaoGlobal)
        self.menuHistograma.addAction(self.actionLimiarizacaoDeOtsu)
        self.menuFiltro.addAction(self.actionFiltroDeMedia)
        self.menuFiltro.addAction(self.actionFiltroDeMediana)
        self.menuFiltro.addAction(self.actionFiltroPassaAlta)
        self.menuFiltro.addAction(self.actionLaplaciano)
        self.menuMorfologia.addAction(self.actionDilatacao)
        self.menuMorfologia.addAction(self.actionErosao)
        self.menuMorfologia.addAction(self.actionAbertura)
        self.menuMorfologia.addAction(self.actionFechamento)
        self.menuSegmentacao.addAction(self.actionSegmentacaoProposta)
        self.menuCaracteristicas.addAction(self.actionExtracaodeCaracteristicas)
        self.menuOCR.addAction(self.actionTransformadaDeHough)
        self.menuOCR.addAction(self.actionCorrecaoDeOrientacao)
        self.menuOCR.addAction(self.actionOCR)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Visao Computacional", None))
        self.actionAbrirImagem1.setText(QCoreApplication.translate("MainWindow", u"Abrir imagem 1", None))
        self.actionAbrirImagem2.setText(QCoreApplication.translate("MainWindow", u"Abrir imagem 2", None))
        self.actionSalvarResultado.setText(QCoreApplication.translate("MainWindow", u"Salvar Resultado", None))
        self.actionSair.setText(QCoreApplication.translate("MainWindow", u"Sair", None))
        self.actionTonsDeCinza.setText(QCoreApplication.translate("MainWindow", u"Tons de Cinza", None))
        self.actionPretoBranco.setText(QCoreApplication.translate("MainWindow", u"Preto e branco", None))
        self.actionSoma.setText(QCoreApplication.translate("MainWindow", u"Soma", None))
        self.actionSubtracao.setText(QCoreApplication.translate("MainWindow", u"Subtra\u00e7\u00e3o", None))
        self.actionMultiplicacao.setText(QCoreApplication.translate("MainWindow", u"Multiplica\u00e7\u00e3o", None))
        self.actionDivisao.setText(QCoreApplication.translate("MainWindow", u"Divis\u00e3o", None))
        self.actionNOT.setText(QCoreApplication.translate("MainWindow", u"NOT", None))
        self.actionAND.setText(QCoreApplication.translate("MainWindow", u"AND", None))
        self.actionOR.setText(QCoreApplication.translate("MainWindow", u"OR", None))
        self.actionXOR.setText(QCoreApplication.translate("MainWindow", u"XOR", None))
        self.actionTranslacao.setText(QCoreApplication.translate("MainWindow", u"Transla\u00e7\u00e3o", None))
        self.actionRotacao.setText(QCoreApplication.translate("MainWindow", u"Rota\u00e7\u00e3o", None))
        self.actionEscalonamento.setText(QCoreApplication.translate("MainWindow", u"Escalonamento", None))
        self.actionDerivativo1.setText(QCoreApplication.translate("MainWindow", u"Derivativo 1", None))
        self.actionDerivativo2.setText(QCoreApplication.translate("MainWindow", u"Derivativo 2", None))
        self.actionSobel.setText(QCoreApplication.translate("MainWindow", u"Sobel", None))
        self.actionKirsch.setText(QCoreApplication.translate("MainWindow", u"Kirsch", None))
        self.actionGerarHistograma.setText(QCoreApplication.translate("MainWindow", u"Gerar Histograma", None))
        self.actionAutoescala.setText(QCoreApplication.translate("MainWindow", u"Autoescala", None))
        self.actionEqualizacaoDeHistograma.setText(QCoreApplication.translate("MainWindow", u"Equaliza\u00e7\u00e3o de Histograma", None))
        self.actionLimiarizacaoGlobal.setText(QCoreApplication.translate("MainWindow", u"Limiariza\u00e7\u00e3o Global", None))
        self.actionLimiarizacaoDeOtsu.setText(QCoreApplication.translate("MainWindow", u"Limiariza\u00e7\u00e3o de Otsu", None))
        self.actionFiltroDeMedia.setText(QCoreApplication.translate("MainWindow", u"Filtro de M\u00e9dia", None))
        self.actionFiltroDeMediana.setText(QCoreApplication.translate("MainWindow", u"Filtro de Mediana", None))
        self.actionFiltroPassaAlta.setText(QCoreApplication.translate("MainWindow", u"Filtro Passa Alta", None))
        self.actionLaplaciano.setText(QCoreApplication.translate("MainWindow", u"Laplaciano", None))
        self.actionDilatacao.setText(QCoreApplication.translate("MainWindow", u"Dilata\u00e7\u00e3o", None))
        self.actionErosao.setText(QCoreApplication.translate("MainWindow", u"Eros\u00e3o", None))
        self.actionAbertura.setText(QCoreApplication.translate("MainWindow", u"Abertura", None))
        self.actionFechamento.setText(QCoreApplication.translate("MainWindow", u"Fechamento", None))
        self.actionSegmentacaoProposta.setText(QCoreApplication.translate("MainWindow", u"Segmenta\u00e7\u00e3o Proposta", None))
        self.actionExtracaodeCaracteristicas.setText(QCoreApplication.translate("MainWindow", u"Extra\u00e7\u00e3o de Caracter\u00edsticas", None))
        self.actionTransformadaDeHough.setText(QCoreApplication.translate("MainWindow", u"Transformada de Hough", None))
        self.actionCorrecaoDeOrientacao.setText(QCoreApplication.translate("MainWindow", u"Corre\u00e7\u00e3o de Orienta\u00e7\u00e3o", None))
        self.actionOCR.setText(QCoreApplication.translate("MainWindow", u"OCR", None))
        self.janela_img1.setText("")
        self.janela_img2.setText("")
        self.janela_img_res.setText("")
        self.janela_img_aux.setText("")
        self.botaoUseResultado.setText(QCoreApplication.translate("MainWindow", u"^", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Imagem 1", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Imagem 2", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Resultado", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Auxiliar", None))
        self.label_Slider_valor.setText(QCoreApplication.translate("MainWindow", u"val", None))
        self.label_Slider_min.setText(QCoreApplication.translate("MainWindow", u"min", None))
        self.label_Slider_max.setText(QCoreApplication.translate("MainWindow", u"max", None))
        self.label_Slider.setText(QCoreApplication.translate("MainWindow", u"Slider", None))
        self.botaoMoveParaAuxiliar.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.menuAbrir.setTitle(QCoreApplication.translate("MainWindow", u"Abrir", None))
        self.menuConverter.setTitle(QCoreApplication.translate("MainWindow", u"Converter", None))
        self.menuOperacoes.setTitle(QCoreApplication.translate("MainWindow", u"Opera\u00e7\u00f5es", None))
        self.menuTransformacoesGeometricas.setTitle(QCoreApplication.translate("MainWindow", u"Transforma\u00e7\u00f5es Geom\u00e9tricas", None))
        self.menuDeteccaodeBordas.setTitle(QCoreApplication.translate("MainWindow", u"Detec\u00e7\u00e3o de Bordas", None))
        self.menuHistograma.setTitle(QCoreApplication.translate("MainWindow", u"Histograma", None))
        self.menuFiltro.setTitle(QCoreApplication.translate("MainWindow", u"Filtro", None))
        self.menuMorfologia.setTitle(QCoreApplication.translate("MainWindow", u"Morfologia", None))
        self.menuSegmentacao.setTitle(QCoreApplication.translate("MainWindow", u"Segmenta\u00e7\u00e3o", None))
        self.menuCaracteristicas.setTitle(QCoreApplication.translate("MainWindow", u"Caracter\u00edsticas", None))
        self.menuOCR.setTitle(QCoreApplication.translate("MainWindow", u"OCR", None))
    # retranslateUi

class Ui_DialogQuestion(object):
    def setupUi(self, DialogQuestion):
        if DialogQuestion.objectName():
            DialogQuestion.setObjectName(u"DialogQuestion")
        DialogQuestion.resize(249, 103)
        self.botaoSim = QPushButton(DialogQuestion)
        self.botaoSim.setObjectName(u"botaoSim")
        self.botaoSim.setGeometry(QRect(10, 60, 101, 23))
        self.botaoNao = QPushButton(DialogQuestion)
        self.botaoNao.setObjectName(u"botaoNao")
        self.botaoNao.setGeometry(QRect(130, 60, 101, 23))
        self.labelPergunta = QLabel(DialogQuestion)
        self.labelPergunta.setObjectName(u"labelPergunta")
        self.labelPergunta.setGeometry(QRect(16, 9, 211, 41))
        self.labelPergunta.setScaledContents(False)
        self.labelPergunta.setAlignment(Qt.AlignCenter)

        self.retranslateUi(DialogQuestion)
        self.botaoSim.clicked.connect(DialogQuestion.accept)
        self.botaoNao.clicked.connect(DialogQuestion.reject)

        QMetaObject.connectSlotsByName(DialogQuestion)
    # setupUi

    def retranslateUi(self, DialogQuestion):
        DialogQuestion.setWindowTitle(QCoreApplication.translate("DialogQuestion", u"Dialog1", None))
        self.botaoSim.setText(QCoreApplication.translate("DialogQuestion", u"Sim", None))
        self.botaoNao.setText(QCoreApplication.translate("DialogQuestion", u"N\u00e3o", None))
        self.labelPergunta.setText(QCoreApplication.translate("DialogQuestion", u"Pergunta", None))
    # retranslateUi

class Ui_DialogTranslacao(object):
    def setupUi(self, DialogTranslacao):
        if DialogTranslacao.objectName():
            DialogTranslacao.setObjectName(u"DialogTranslacao")
        DialogTranslacao.resize(196, 228)
        self.labeldy = QLabel(DialogTranslacao)
        self.labeldy.setObjectName(u"labeldy")
        self.labeldy.setGeometry(QRect(50, 90, 71, 16))
        self.labeldx = QLabel(DialogTranslacao)
        self.labeldx.setObjectName(u"labeldx")
        self.labeldx.setGeometry(QRect(50, 20, 81, 16))
        self.botaoOk = QPushButton(DialogTranslacao)
        self.botaoOk.setObjectName(u"botaoOk")
        self.botaoOk.setGeometry(QRect(10, 190, 75, 23))
        self.botaoCancelar = QPushButton(DialogTranslacao)
        self.botaoCancelar.setObjectName(u"botaoCancelar")
        self.botaoCancelar.setGeometry(QRect(110, 190, 75, 23))
        self.caixadx = QDoubleSpinBox(DialogTranslacao)
        self.caixadx.setObjectName(u"caixadx")
        self.caixadx.setGeometry(QRect(50, 40, 62, 22))
        self.caixadx.setDecimals(2)
        self.caixadx.setMinimum(-100000.000000000000000)
        self.caixadx.setMaximum(100000.000000000000000)
        self.caixadx.setSingleStep(0.100000000000000)
        self.caixady = QDoubleSpinBox(DialogTranslacao)
        self.caixady.setObjectName(u"caixady")
        self.caixady.setGeometry(QRect(50, 110, 62, 22))
        self.caixady.setDecimals(2)
        self.caixady.setMinimum(-100000.000000000000000)
        self.caixady.setMaximum(100000.000000000000000)
        self.caixady.setSingleStep(0.100000000000000)
        QWidget.setTabOrder(self.caixadx, self.caixady)
        QWidget.setTabOrder(self.caixady, self.botaoOk)
        QWidget.setTabOrder(self.botaoOk, self.botaoCancelar)

        self.retranslateUi(DialogTranslacao)
        self.botaoOk.clicked.connect(DialogTranslacao.accept)
        self.botaoCancelar.clicked.connect(DialogTranslacao.reject)

        QMetaObject.connectSlotsByName(DialogTranslacao)
    # setupUi

    def retranslateUi(self, DialogTranslacao):
        DialogTranslacao.setWindowTitle(QCoreApplication.translate("DialogTranslacao", u"Transla\u00e7\u00e3o", None))
        self.labeldy.setText(QCoreApplication.translate("DialogTranslacao", u"dy:", None))
        self.labeldx.setText(QCoreApplication.translate("DialogTranslacao", u"dx:", None))
        self.botaoOk.setText(QCoreApplication.translate("DialogTranslacao", u"Ok", None))
        self.botaoCancelar.setText(QCoreApplication.translate("DialogTranslacao", u"Cancelar", None))
        self.caixadx.setSuffix("")
        self.caixady.setSuffix("")
    # retranslateUi

class Ui_DialogRotacao(object):
    def setupUi(self, DialogRotacao):
        if DialogRotacao.objectName():
            DialogRotacao.setObjectName(u"DialogRotacao")
        DialogRotacao.resize(217, 297)
        self.labelAngulo = QLabel(DialogRotacao)
        self.labelAngulo.setObjectName(u"labelAngulo")
        self.labelAngulo.setGeometry(QRect(60, 20, 47, 13))
        self.labelCoordX = QLabel(DialogRotacao)
        self.labelCoordX.setObjectName(u"labelCoordX")
        self.labelCoordX.setGeometry(QRect(60, 100, 81, 16))
        self.labelCoordY = QLabel(DialogRotacao)
        self.labelCoordY.setObjectName(u"labelCoordY")
        self.labelCoordY.setGeometry(QRect(60, 180, 81, 16))
        self.caixaAngulo = QDoubleSpinBox(DialogRotacao)
        self.caixaAngulo.setObjectName(u"caixaAngulo")
        self.caixaAngulo.setGeometry(QRect(60, 40, 62, 22))
        self.caixaAngulo.setDecimals(1)
        self.caixaAngulo.setMinimum(-180.000000000000000)
        self.caixaAngulo.setMaximum(180.000000000000000)
        self.caixaAngulo.setSingleStep(0.100000000000000)
        self.caixaCoordX = QSpinBox(DialogRotacao)
        self.caixaCoordX.setObjectName(u"caixaCoordX")
        self.caixaCoordX.setGeometry(QRect(60, 120, 42, 22))
        self.caixaCoordX.setMinimum(0)
        self.caixaCoordX.setMaximum(100)
        self.caixaCoordX.setValue(0)
        self.caixaCoordY = QSpinBox(DialogRotacao)
        self.caixaCoordY.setObjectName(u"caixaCoordY")
        self.caixaCoordY.setGeometry(QRect(60, 200, 42, 22))
        self.caixaCoordY.setMinimum(0)
        self.caixaCoordY.setMaximum(100)
        self.caixaCoordY.setValue(0)
        self.botaoOk = QPushButton(DialogRotacao)
        self.botaoOk.setObjectName(u"botaoOk")
        self.botaoOk.setGeometry(QRect(20, 260, 75, 23))
        self.botaoCancelar = QPushButton(DialogRotacao)
        self.botaoCancelar.setObjectName(u"botaoCancelar")
        self.botaoCancelar.setGeometry(QRect(120, 260, 75, 23))

        self.retranslateUi(DialogRotacao)
        self.botaoOk.clicked.connect(DialogRotacao.accept)
        self.botaoCancelar.clicked.connect(DialogRotacao.reject)

        QMetaObject.connectSlotsByName(DialogRotacao)
    # setupUi

    def retranslateUi(self, DialogRotacao):
        DialogRotacao.setWindowTitle(QCoreApplication.translate("DialogRotacao", u"Rota\u00e7\u00e3o", None))
        self.labelAngulo.setText(QCoreApplication.translate("DialogRotacao", u"\u00c2ngulo:", None))
        self.labelCoordX.setText(QCoreApplication.translate("DialogRotacao", u"Coordenada X:", None))
        self.labelCoordY.setText(QCoreApplication.translate("DialogRotacao", u"Coordenanda Y:", None))
        self.caixaAngulo.setSuffix(QCoreApplication.translate("DialogRotacao", u"\u00ba", None))
        self.botaoOk.setText(QCoreApplication.translate("DialogRotacao", u"Ok", None))
        self.botaoCancelar.setText(QCoreApplication.translate("DialogRotacao", u"Cancelar", None))
    # retranslateUi

class Ui_DialogEscalonamento(object):
    def setupUi(self, DialogEscalonamento):
        if DialogEscalonamento.objectName():
            DialogEscalonamento.setObjectName(u"DialogEscalonamento")
        DialogEscalonamento.resize(204, 340)
        self.botaoOk = QPushButton(DialogEscalonamento)
        self.botaoOk.setObjectName(u"botaoOk")
        self.botaoOk.setGeometry(QRect(10, 310, 75, 23))
        self.botaoCancelar = QPushButton(DialogEscalonamento)
        self.botaoCancelar.setObjectName(u"botaoCancelar")
        self.botaoCancelar.setGeometry(QRect(110, 310, 75, 23))
        self.labelEscalaY = QLabel(DialogEscalonamento)
        self.labelEscalaY.setObjectName(u"labelEscalaY")
        self.labelEscalaY.setGeometry(QRect(50, 90, 71, 16))
        self.labelCoordY = QLabel(DialogEscalonamento)
        self.labelCoordY.setObjectName(u"labelCoordY")
        self.labelCoordY.setGeometry(QRect(50, 230, 81, 16))
        self.caixaEscalaY = QDoubleSpinBox(DialogEscalonamento)
        self.caixaEscalaY.setObjectName(u"caixaEscalaY")
        self.caixaEscalaY.setGeometry(QRect(50, 110, 62, 22))
        self.caixaEscalaY.setDecimals(2)
        self.caixaEscalaY.setMinimum(-100000.000000000000000)
        self.caixaEscalaY.setMaximum(100000.000000000000000)
        self.caixaEscalaY.setSingleStep(0.100000000000000)
        self.caixaCoordY = QSpinBox(DialogEscalonamento)
        self.caixaCoordY.setObjectName(u"caixaCoordY")
        self.caixaCoordY.setGeometry(QRect(50, 250, 42, 22))
        self.caixaCoordY.setMinimum(0)
        self.caixaCoordY.setMaximum(100)
        self.caixaCoordY.setValue(0)
        self.caixaCoordX = QSpinBox(DialogEscalonamento)
        self.caixaCoordX.setObjectName(u"caixaCoordX")
        self.caixaCoordX.setGeometry(QRect(50, 180, 42, 22))
        self.caixaCoordX.setMinimum(0)
        self.caixaCoordX.setMaximum(100)
        self.caixaCoordX.setValue(0)
        self.labelCoordX = QLabel(DialogEscalonamento)
        self.labelCoordX.setObjectName(u"labelCoordX")
        self.labelCoordX.setGeometry(QRect(50, 160, 81, 16))
        self.labelEscalaX = QLabel(DialogEscalonamento)
        self.labelEscalaX.setObjectName(u"labelEscalaX")
        self.labelEscalaX.setGeometry(QRect(50, 20, 81, 16))
        self.caixaEscalaX = QDoubleSpinBox(DialogEscalonamento)
        self.caixaEscalaX.setObjectName(u"caixaEscalaX")
        self.caixaEscalaX.setGeometry(QRect(50, 40, 62, 22))
        self.caixaEscalaX.setDecimals(2)
        self.caixaEscalaX.setMinimum(-100000.000000000000000)
        self.caixaEscalaX.setMaximum(100000.000000000000000)
        self.caixaEscalaX.setSingleStep(0.100000000000000)
        QWidget.setTabOrder(self.caixaEscalaX, self.caixaEscalaY)
        QWidget.setTabOrder(self.caixaEscalaY, self.caixaCoordX)
        QWidget.setTabOrder(self.caixaCoordX, self.caixaCoordY)
        QWidget.setTabOrder(self.caixaCoordY, self.botaoOk)
        QWidget.setTabOrder(self.botaoOk, self.botaoCancelar)

        self.retranslateUi(DialogEscalonamento)
        self.botaoOk.clicked.connect(DialogEscalonamento.accept)
        self.botaoCancelar.clicked.connect(DialogEscalonamento.reject)

        QMetaObject.connectSlotsByName(DialogEscalonamento)
    # setupUi

    def retranslateUi(self, DialogEscalonamento):
        DialogEscalonamento.setWindowTitle(QCoreApplication.translate("DialogEscalonamento", u"Escalonamento", None))
        self.botaoOk.setText(QCoreApplication.translate("DialogEscalonamento", u"Ok", None))
        self.botaoCancelar.setText(QCoreApplication.translate("DialogEscalonamento", u"Cancelar", None))
        self.labelEscalaY.setText(QCoreApplication.translate("DialogEscalonamento", u"Escala em Y:", None))
        self.labelCoordY.setText(QCoreApplication.translate("DialogEscalonamento", u"Coordenanda Y:", None))
        self.caixaEscalaY.setSuffix("")
        self.labelCoordX.setText(QCoreApplication.translate("DialogEscalonamento", u"Coordenada X:", None))
        self.labelEscalaX.setText(QCoreApplication.translate("DialogEscalonamento", u"Escala em X:", None))
        self.caixaEscalaX.setSuffix("")
    # retranslateUi

class Ui_DialogFiltroMedia(object):
    def setupUi(self, DialogFiltroMedia):
        if DialogFiltroMedia.objectName():
            DialogFiltroMedia.setObjectName(u"DialogFiltroMedia")
        DialogFiltroMedia.resize(199, 239)
        self.botaoOk = QPushButton(DialogFiltroMedia)
        self.botaoOk.setObjectName(u"botaoOk")
        self.botaoOk.setGeometry(QRect(10, 200, 75, 23))
        self.botaoCancelar = QPushButton(DialogFiltroMedia)
        self.botaoCancelar.setObjectName(u"botaoCancelar")
        self.botaoCancelar.setGeometry(QRect(110, 200, 75, 23))
        self.caixaLinhas = QSpinBox(DialogFiltroMedia)
        self.caixaLinhas.setObjectName(u"caixaLinhas")
        self.caixaLinhas.setGeometry(QRect(30, 90, 42, 22))
        self.caixaLinhas.setMinimum(3)
        self.caixaLinhas.setMaximum(10000)
        self.caixaColunas = QSpinBox(DialogFiltroMedia)
        self.caixaColunas.setObjectName(u"caixaColunas")
        self.caixaColunas.setGeometry(QRect(30, 150, 42, 22))
        self.caixaColunas.setMinimum(3)
        self.caixaColunas.setMaximum(10000)
        self.labelLinhas = QLabel(DialogFiltroMedia)
        self.labelLinhas.setObjectName(u"labelLinhas")
        self.labelLinhas.setGeometry(QRect(30, 60, 47, 13))
        self.labelColunas = QLabel(DialogFiltroMedia)
        self.labelColunas.setObjectName(u"labelColunas")
        self.labelColunas.setGeometry(QRect(30, 130, 47, 13))
        self.label = QLabel(DialogFiltroMedia)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 171, 31))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)

        self.retranslateUi(DialogFiltroMedia)
        self.botaoOk.clicked.connect(DialogFiltroMedia.accept)
        self.botaoCancelar.clicked.connect(DialogFiltroMedia.reject)

        QMetaObject.connectSlotsByName(DialogFiltroMedia)
    # setupUi

    def retranslateUi(self, DialogFiltroMedia):
        DialogFiltroMedia.setWindowTitle(QCoreApplication.translate("DialogFiltroMedia", u"Filtro de M\u00e9dia", None))
        self.botaoOk.setText(QCoreApplication.translate("DialogFiltroMedia", u"Ok", None))
        self.botaoCancelar.setText(QCoreApplication.translate("DialogFiltroMedia", u"Cancelar", None))
        self.labelLinhas.setText(QCoreApplication.translate("DialogFiltroMedia", u"Linhas:", None))
        self.labelColunas.setText(QCoreApplication.translate("DialogFiltroMedia", u"Colunas:", None))
        self.label.setText(QCoreApplication.translate("DialogFiltroMedia", u"Escolha a dimens\u00e3o do filtro", None))
    # retranslateUi

class Ui_ElementoEstruturante(QDialog):
    def setupUi(self, ElementoEstruturante):
        if ElementoEstruturante.objectName():
            ElementoEstruturante.setObjectName(u"ElementoEstruturante")
        ElementoEstruturante.resize(400, 423)
        self.gridLayout_2 = QGridLayout(ElementoEstruturante)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.botaoOk = QPushButton(ElementoEstruturante)
        self.botaoOk.setObjectName(u"botaoOk")
        self.gridLayout_2.addWidget(self.botaoOk, 1, 0, 1, 1)
        self.botaoCancelar = QPushButton(ElementoEstruturante)
        self.botaoCancelar.setObjectName(u"botaoCancelar")
        self.gridLayout_2.addWidget(self.botaoCancelar, 1, 1, 1, 1)

        self.retranslateUi(ElementoEstruturante)
        self.botaoOk.clicked.connect(ElementoEstruturante.accept)
        self.botaoCancelar.clicked.connect(ElementoEstruturante.reject)

        QMetaObject.connectSlotsByName(ElementoEstruturante)
    # setupUi

    def retranslateUi(self, ElementoEstruturante):
        ElementoEstruturante.setWindowTitle(QCoreApplication.translate("ElementoEstruturante", u"Elemento Estruturante", None))
        self.botaoOk.setText(QCoreApplication.translate("ElementoEstruturante", u"Ok", None))
        self.botaoCancelar.setText(QCoreApplication.translate("ElementoEstruturante", u"Cancelar", None))
    # retranslateUi

class Ui_JanelaRegioes(QWidget):
    def __init__(self):
        super(Ui_JanelaRegioes, self).__init__()
        self.setupUi(self)

    def setupUi(self, janelaRegioes):
        if janelaRegioes.objectName():
            janelaRegioes.setObjectName(u"janelaRegioes")
        janelaRegioes.resize(234, 270)
        self.formLayout = QFormLayout(janelaRegioes)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.caixaRegioes = QPlainTextEdit(janelaRegioes)
        self.caixaRegioes.setObjectName(u"caixaRegioes")
        self.caixaRegioes.setAcceptDrops(False)
        self.caixaRegioes.setFrameShadow(QFrame.Sunken)
        self.caixaRegioes.setReadOnly(True)

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.caixaRegioes)


        self.retranslateUi(janelaRegioes)

        QMetaObject.connectSlotsByName(janelaRegioes)
    # setupUi

    def retranslateUi(self, janelaRegioes):
        janelaRegioes.setWindowTitle(QCoreApplication.translate("janelaRegioes", u"Regi\u00f5es", None))
        self.caixaRegioes.setPlainText("")
    # retranslateUi

class MyQuestion(QDialog):
    def __init__(self,titulo,pergunta):
        super(MyQuestion, self).__init__()
        self.uiDialogue = Ui_DialogQuestion()
        self.uiDialogue.setupUi(self)
        self.setWindowTitle(titulo)
        self.uiDialogue.labelPergunta.setText(pergunta)

class MinhaTranslacao(QDialog):
    def __init__(self):
        super(MinhaTranslacao, self).__init__()
        self.uiTranslacao = Ui_DialogTranslacao()
        self.uiTranslacao.setupUi(self)

    def getValores(self):
        return (self.uiTranslacao.caixadx.value(),self.uiTranslacao.caixady.value())

class MinhaRotacao(QDialog):
    def __init__(self,numeroX,numeroY):
        super(MinhaRotacao, self).__init__()
        self.uiRotacao = Ui_DialogRotacao()
        self.uiRotacao.setupUi(self)
        self.uiRotacao.caixaCoordX.setMaximum(numeroX-1)
        self.uiRotacao.caixaCoordX.setValue(int(numeroX/2))
        self.uiRotacao.caixaCoordY.setMaximum(numeroY-1)
        self.uiRotacao.caixaCoordY.setValue(int(numeroY/2))

    def getValores(self):
        return (self.uiRotacao.caixaAngulo.value(),self.uiRotacao.caixaCoordX.value(),self.uiRotacao.caixaCoordY.value())

class MeuEscalonamento(QDialog):
    def __init__(self,numeroX,numeroY):
        super(MeuEscalonamento, self).__init__()
        self.uiEscalonamento = Ui_DialogEscalonamento()
        self.uiEscalonamento.setupUi(self)
        self.uiEscalonamento.caixaCoordX.setMaximum(numeroX-1)
        self.uiEscalonamento.caixaCoordX.setValue(int(numeroX/2))
        self.uiEscalonamento.caixaCoordY.setMaximum(numeroY-1)
        self.uiEscalonamento.caixaCoordY.setValue(int(numeroY/2))

    def getValores(self):
        return (self.uiEscalonamento.caixaEscalaX.value(),self.uiEscalonamento.caixaEscalaY.value(),self.uiEscalonamento.caixaCoordX.value(),self.uiEscalonamento.caixaCoordY.value())

class MeuFiltroMedia(QDialog):
    def __init__(self):
        super(MeuFiltroMedia, self).__init__()
        self.uiFiltroMedia = Ui_DialogFiltroMedia()
        self.uiFiltroMedia.setupUi(self)

    def getValores(self):
        return(self.uiFiltroMedia.caixaLinhas.value(),self.uiFiltroMedia.caixaColunas.value())

class MeuBotao(QPushButton):
    def __init__(self):
        super(MeuBotao, self).__init__()
        self.setText("")
        self.setCheckable(True)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

class MeuElementoEstruturante(QDialog):
    def __init__(self,N):
        super(MeuElementoEstruturante, self).__init__()
        self.uiElementoEstruturante = Ui_ElementoEstruturante()
        self.uiElementoEstruturante.setupUi(self)
        self.dim = N
        self.botoes = {}
        for i in range(N):
            for j in range(N):
                self.botoes[i,j] = MeuBotao()
                self.uiElementoEstruturante.gridLayout.addWidget(self.botoes[i,j],i,j)

    def getMatriz(self):
        matriz = np.zeros([self.dim,self.dim])
        for i in range(self.dim):
            for j in range(self.dim):
                if self.botoes[i,j].isChecked():
                    matriz[i,j] = 1

        return matriz

class MinhaJanela(QWidget):
    def __init__(self):
        super(MinhaJanela, self).__init__()
        self.uiJanela = Ui_JanelaRegioes()
        self.uiJanela.setupUi(self)
